fix: release only for three main platforms
Because there are problems on other platforms:
error[E0463]: can't find crate for `rustc_interface`
 --> src/main.rs:7:1
  |
7 | extern crate rustc_interface;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
  |
  = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`